### PR TITLE
parity with read me and other stuff

### PR DESCRIPTION
**Pull request by SirGamers**
dunno why it's checking if it can build and publish the mod reloaded because all I did with the file was change  but no code

### CODE REVIEW

**Review by SirGamers — COMMENTED** [review]
why this failed the check idk

**Comment by Sewer56** [comment]
Only thing to note, when writing `bit` in `64 bit` make sure B is lowercase (it is actually important).

Otherwise looks good to me

**Comment by SirGamers** [comment]
> Only thing to note, when writing `bit` in `64 bit` make sure B is lowercase (it is actually important).
> 
> Otherwise looks good to me

let me change that real quick

**Comment by SirGamers** [comment]
> 

fixed

**Review by Sewer56 — APPROVED** [review]

**Pull request merged**
